### ISSUE TITLE
 SyntaxError on running InstaPy

### ISSUE THREAD

**Issue by cryp70n1ccc** [InstaPy/instapy-docs#16]
python quickstart.py

Traceback (most recent call last):
  File "quickstart.py", line 4, in <module>
    from instapy import InstaPy
  File "/home/cryp70n1c/Videos/InstaPy/instapy/__init__.py", line 6, in <module>
    from .instapy import InstaPy
  File "/home/cryp70n1c/Videos/InstaPy/instapy/instapy.py", line 99
    username: str = None,
            ^
SyntaxError: invalid syntax

**Comment by nomadeprogramador** [comment]
you missed something in your code syntax, pay attention to the punctuation and see if you didn't use any reserved words incorrectly.

**Comment by clement-gaudiniere** [comment]
same

**Comment by clement-gaudiniere** [comment]
I managed to solve the problem by changing the version of the python interpreter in VS CODE
