### ISSUE TITLE
Raspberry Pi Installation issue

### ISSUE THREAD

**Issue by federicozanini** [InstaPy/instapy-docs#20]
Hi!
I'm trying to install instaPy on my raspberry and I followed your [guide](https://github.com/InstaPy/instapy-docs/blob/master/How_Tos/How_to_Raspberry.md) in order to do it, but unfortunately I'm running into this error when I try I run: `sudo python3 quickstart.py` and I don't know what to do:
`InstaPy Version: 0.6.8
 ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/root/InstaPy"
Traceback (most recent call last):
  File "quickstart.py", line 33, in <module>
    headless_browser=True)
  File "/usr/local/lib/python3.7/dist-packages/instapy/instapy.py", line 319, in __init__
    self.logger,
  File "/usr/local/lib/python3.7/dist-packages/instapy/browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/common/service.py", line 111, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service /usr/local/bin/geckodriver unexpectedly exited. Status code was: -11
`

Thanks for the help!

**Comment by federicozanini** [comment]
I'm still trying by myself and I think the problem is GeckoDriver not working properly on my Raspberry Pi model B. How can I understand which geckodriver/firefox-esr combination is good for me?

**Comment by AlejandroDieg0** [comment]
you can try setting headless mode = True
