### ISSUE TITLE
Don't works, can't start quickstart.py

### ISSUE THREAD

**Issue by JoCluzet42** [InstaPy/instapy-docs#23]
Hi, 
When i launch the quickstart.py script, I always seen the same error, for me or my friends testing InstaPy.

If anyone have an issues.. Thanks !

`Error, unable to determine correct filename for 64bit linux
Traceback (most recent call last):
  File "quickstart.py", line 14, in <module>
    session = InstaPy(username=insta_username,
  File "/usr/local/lib/python3.8/dist-packages/instapy/instapy.py", line 322, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "/usr/local/lib/python3.8/dist-packages/instapy/browser.py", line 131, in set_selenium_local_session
    driver_path = geckodriver_path or get_geckodriver()
  File "/usr/local/lib/python3.8/dist-packages/instapy/browser.py", line 38, in get_geckodriver
    sym_path = gdd.download_and_install()[1]
  File "/usr/local/lib/python3.8/dist-packages/webdriverdownloader/webdriverdownloader.py", line 174, in download_and_install
    filename_with_path = self.download(version,
  File "/usr/local/lib/python3.8/dist-packages/webdriverdownloader/webdriverdownloader.py", line 129, in download
    download_url = self.get_download_url(version, os_name=os_name, bitness=bitness)
  File "/usr/local/lib/python3.8/dist-packages/webdriverdownloader/webdriverdownloader.py", line 324, in get_download_url
    raise RuntimeError(info_message)
RuntimeError: Error, unable to determine correct filename for 64bit linux`

**Comment by orhan-drsn** [comment]
Same issue

**Comment by billpsomas** [comment]
This problem is not related to InstaPy but the webdriverdownloader.py from webdriverdownloader. 

For Ubuntu you can fix the problem with sudo apt install firefox-geckodriver.
Other OS will have similar solution to install the geckodirver.
