### ISSUE TITLE
Service geckodriver unexpectedly exited. Status code was: -11

### ISSUE THREAD

**Issue by mamk02** [InstaPy/instapy-docs#26]
I have followed all the instructions to install instapy onto my raspberry pi zero w and i get this error:

`InstaPy Version: 0.6.12
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "/home/pi/InstaPy"
Traceback (most recent call last):
  File "quickstart.py", line 59, in <module>
    multi_logs=True)
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/instapy.py", line 335, in __init__
    geckodriver_log_level,
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/browser.py", line 136, in set_selenium_local_session
    options=firefox_options,
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 111, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service /usr/local/bin/geckodriver unexpectedly exited. Status code was: -11`

**Comment by AxelRP** [comment]
Not sure if you are still with this.. but I had the same problem and it seems raspberry pi zero w cannot run Firefox ESR (or at least I couldn't make it work). As I understood, it is something related to Firefox being build for ARMv7 processors, and Zero it's ARMv6.
Again, I'm not sure what I'm saying is correct, but I switched to the Raspberry Pi 3 B+ and everything works fine now
