### ISSUE TITLE
Noob raspberry pi errors..  selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

### ISSUE THREAD

**Issue by cazamatte** [InstaPy/instapy-docs#28]
Followed all the instructions in guide for installing on a pi.
running latest version of Raspbian. 
InstaPy Version: 0.6.13, 
Mozilla Firefox 78.6.1esr, 
Python 2.7.16, 
Lastest selenium (can't work out how to  check that..)
Geckodriver 0.23.0 downloaded and tried in /usr/bin and /usr/local/bin neither changed the erros and both on $PATH

Please can someone suggest how I could fix it. At the moment nothing manages to load it just crashes with the errors below. Problems I thought of but i don't know how to fix; Geckodriver version not working with current firefox version? Location of Geckodriver needing specified somehow? 

Or maybe I messed up something else.... ? I can't get it working running either with a test script or instapy quickstart.

Workspace in use: "/home/pi/InstaPy"
Traceback (most recent call last):
  File "quickstart.py", line 24, in <module>
    headless_browser=False)
  File "/usr/local/lib/python3.7/dist-packages/instapy/instapy.py", line 338, in __init__
    geckodriver_log_level,
  File "/usr/local/lib/python3.7/dist-packages/instapy/browser.py", line 127, in set_selenium_local_session
    options=firefox_options,
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by cazamatte** [comment]
Edit using Selenium 3.141.0, Python 3.7.3
